# fly.toml app configuration file
#
app = "taxupdater"
primary_region = "nrt"

[build]

[env]
  PORT = "8080"
  TZ = "Asia/Seoul"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[services.http_checks]]
  interval = "30s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  restart_limit = 0
  timeout = "2s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "taxupdater_data"
  destination = "/data"